import type { NextPage } from 'next';
import Head from 'next/head';

import SearchInput from '@Components/Search';
import ProductCard from '@/components/ProductCard';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchInput />
      <ProductCard />
    </>
  );
};

export default Home;

